### ISSUE TITLE
Unable to Paste Token

### ISSUE THREAD

**Issue by simondmorias** [DataThirstLtd/DBFS-Explorer#18]
On a Mac you cannot paste a token into the Bearer token field on the first authentication screen. For some reason paste seems to be disabled.

**Comment by saikksub** [comment]
Okay. I will work on it.

**Comment by saikksub** [comment]
Fixed. Please use `dev` branch and build the application. I have added application menu to enable;e generic operations (Copy, Paste, Cut, etc).

**Comment by simondmorias** [comment]
Thanks Sai - appreciate that a lot. Will look shorty
