### ISSUE TITLE
No scrolling in file explorer

### ISSUE THREAD

**Issue by sthupakula-rms** [DataThirstLtd/DBFS-Explorer#29]
I am unable to scroll down in the windows version of the app. Neither in the side bar nor in the main explorer windows. Am I doing something wrong?
ST.

**Comment by saikksub** [comment]
Thank you for reporting the issue. I will review and let you know.

**Comment by saikksub** [comment]
Fixed scroll down issue with new commit.

**Comment by sthupakula-rms** [comment]
Thank you. Can I just reinstall the executable from https://datathirst.net/projects/dbfs-explorer/ to get the updates?

**Comment by simondmorias** [comment]
You can


________________________________

**Comment by sthupakula-rms** [comment]
Thank you. Scroll works :)
